### ISSUE TITLE
Late penalities

### ISSUE THREAD

**Issue by ausbin** [zucchini/zucchini#28]
compare the submission times to due dates and take off N points if they're late

**Comment by skyman** [comment]
Would be good to allow multiplier deductions too, like instead of taking off a flat .25 of the full assignment it can be .25 of what the student received.

Also potentially allow multi-tiered deductions - different deductions for different points in time?

**Comment by ausbin** [comment]
any ideas for the config format for that? Drawing a blank

**Comment by skyman** [comment]
Something like this maybe? This would go in the Canvas part of the config:
```yml
late-deductions:
    - after: 2018-01-11T23:55:00-05:00
      deduct: 0.5
    - after: 2018-01-12T01:55:00-05:00
      deduct: 0.1
    - after: 2018-01-12T05:55:00-05:00
      deduct: 0.1
```

So they get added up until the current time - like if the submission is after 1/12/18 5.55am above, you end up losing a flat 0.25, and we can use % signs for multiplier?

**Comment by skyman** [comment]
They can also use the Canvas deadline and be set up as relative dates on that one though so if we extend the thing we dont need to modify the config

**Comment by skyman** [comment]
```yml
late-deductions:
    - after-deadline: 0s
      deduct: 0.5
    - after-deadline: 2h
      deduct: 0.1
    - after-deadline: 6h
      deduct: 0.1
```
